[package]
name = "realethanplayzdev/builder"
description = "An instance building system"
license = "MIT"
authors = ["RadiatedExodus (RealEthanPlayzDev) <radiatedexodus@gmail.com>"]
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]