[package]
name = "radiatedexodus/builder"
description = "An instance building system"
license = "MIT"
authors = ["RealEthanPlayzDev (RadiatedExodus)"]
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
